[package]
name = "rust-am-comms-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
rust_am_lib = {workspace = true}
serde_json = { workspace = true }
lib = {path = "../../lib"}
tokio = { version = "1.44.2", features = ["full"] }