[package]
name = "rust-am-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
rust_am_lib = {workspace = true}
serde_json = { workspace = true }
sha2 = "0.10.8"
lib = {path = "../../lib"}
