[package]
name = "rust-asp-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
rust_am_lib = {workspace = true}
lib = {path = "../../lib"}